// <auto-generated />
using System;
using Agenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenda.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328144504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            Description = "Revisión del sprint actual",
                            EndDate = new DateTime(2026, 3, 28, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5249),
                            Location = "Oficina",
                            Name = "Sprint Review",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 8, 45, 3, 904, DateTimeKind.Local).AddTicks(5233),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            Description = "Discusión de arquitectura",
                            EndDate = new DateTime(2026, 3, 28, 13, 45, 3, 904, DateTimeKind.Local).AddTicks(5252),
                            Location = "Zoom",
                            Name = "Reunión técnica",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 9, 45, 3, 904, DateTimeKind.Local).AddTicks(5251),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            Description = "Repechaje mundialista",
                            EndDate = new DateTime(2026, 3, 29, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5255),
                            Location = "Estadio Hernando Siles",
                            Name = "Partido Bolivia vs Surinam",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 29, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5253),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            Description = "Presentación del sistema",
                            EndDate = new DateTime(2026, 3, 30, 11, 45, 3, 904, DateTimeKind.Local).AddTicks(5257),
                            Location = "Oficina",
                            Name = "Demo al cliente",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 30, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5257),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            Description = "Rutina gym",
                            EndDate = new DateTime(2026, 3, 31, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5260),
                            Location = "Gym",
                            Name = "Entrenamiento personal",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 31, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5259),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 1,
                            Description = "Salida social",
                            EndDate = new DateTime(2026, 4, 1, 13, 45, 3, 904, DateTimeKind.Local).AddTicks(5262),
                            Location = "Restaurante",
                            Name = "Cena con amigos",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 4, 1, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5262),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 1,
                            Description = "Capacitación frontend",
                            EndDate = new DateTime(2026, 3, 23, 13, 45, 3, 904, DateTimeKind.Local).AddTicks(5265),
                            Location = "Centro TI",
                            Name = "Curso de Angular",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 23, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5264),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 1,
                            Description = "Amistoso internacional",
                            EndDate = new DateTime(2026, 3, 25, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5267),
                            Location = "Estadio",
                            Name = "Partido Bolivia vs Perú",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 25, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5266),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = 1,
                            Description = "Liberación versión 1.0",
                            EndDate = new DateTime(2026, 3, 26, 11, 45, 3, 904, DateTimeKind.Local).AddTicks(5269),
                            Location = "Servidor",
                            Name = "Deploy producción",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 26, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5269),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = 2,
                            Description = "Reunión diaria",
                            EndDate = new DateTime(2026, 3, 28, 11, 45, 3, 904, DateTimeKind.Local).AddTicks(5272),
                            Location = "Teams",
                            Name = "Daily Scrum",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 9, 45, 3, 904, DateTimeKind.Local).AddTicks(5271),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatorId = 2,
                            Description = "Resolución de bugs",
                            EndDate = new DateTime(2026, 3, 28, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5274),
                            Location = "Oficina",
                            Name = "Debug sesión",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 8, 45, 3, 904, DateTimeKind.Local).AddTicks(5274),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatorId = 2,
                            Description = "Organización tareas",
                            EndDate = new DateTime(2026, 3, 29, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5277),
                            Location = "Zoom",
                            Name = "Planificación sprint",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 29, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5276),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatorId = 2,
                            Description = "Partido entre amigos",
                            EndDate = new DateTime(2026, 3, 30, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5279),
                            Location = "Cancha",
                            Name = "Partido fútbol",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 30, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5278),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatorId = 2,
                            Description = "Reunión familiar",
                            EndDate = new DateTime(2026, 3, 31, 13, 45, 3, 904, DateTimeKind.Local).AddTicks(5281),
                            Location = "Casa",
                            Name = "Cena familiar",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 31, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5281),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatorId = 2,
                            Description = "Code review",
                            EndDate = new DateTime(2026, 4, 1, 11, 45, 3, 904, DateTimeKind.Local).AddTicks(5284),
                            Location = "GitHub",
                            Name = "Revisión código",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 4, 1, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5283),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatorId = 2,
                            Description = "Corrección urgente",
                            EndDate = new DateTime(2026, 3, 24, 11, 45, 3, 904, DateTimeKind.Local).AddTicks(5286),
                            Location = "Servidor",
                            Name = "Deploy hotfix",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 24, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5286),
                            Status = true,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatorId = 2,
                            Description = "Feedback sistema",
                            EndDate = new DateTime(2026, 3, 25, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5289),
                            Location = "Oficina",
                            Name = "Reunión cliente",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 25, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5288),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatorId = 2,
                            Description = "Pruebas del sistema",
                            EndDate = new DateTime(2026, 3, 26, 12, 45, 3, 904, DateTimeKind.Local).AddTicks(5291),
                            Location = "QA Lab",
                            Name = "Testing QA",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 26, 10, 45, 3, 904, DateTimeKind.Local).AddTicks(5290),
                            Status = true,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 2,
                            ReceiverId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 3,
                            ReceiverId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            EventId = 6,
                            ReceiverId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            EventId = 8,
                            ReceiverId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            EventId = 11,
                            ReceiverId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            EventId = 13,
                            ReceiverId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            EventId = 15,
                            ReceiverId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            EventId = 17,
                            ReceiverId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Admin",
                            Email = "douglash.dcz@gmail.com",
                            Password = "YWRtaW4xMjM=",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "John",
                            Email = "juan@gmail.com",
                            Password = "anVhbjEyMw==",
                            Username = "juan"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Maria",
                            Email = "maria@gmail.com",
                            Password = "bWFyaWExMjM=",
                            Username = "maria"
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Carlos",
                            Email = "carlos@gmail.com",
                            Password = "Y2FybG9zMTIz",
                            Username = "carlos"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Event", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.User", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
