// <auto-generated />
using System;
using Agenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenda.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Agenda.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            Description = "Revisión del sprint actual",
                            EndDate = new DateTime(2026, 3, 24, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8034),
                            Location = "Oficina",
                            Name = "Sprint Review",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 24, 12, 52, 45, 565, DateTimeKind.Local).AddTicks(8016),
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            Description = "Discusión de arquitectura",
                            EndDate = new DateTime(2026, 3, 24, 17, 52, 45, 565, DateTimeKind.Local).AddTicks(8037),
                            Location = "Zoom",
                            Name = "Reunión técnica",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 24, 13, 52, 45, 565, DateTimeKind.Local).AddTicks(8037),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            Description = "Repechaje mundialista",
                            EndDate = new DateTime(2026, 3, 25, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8041),
                            Location = "Estadio Hernando Siles",
                            Name = "Partido Bolivia vs Surinam",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 25, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8039),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            Description = "Presentación del sistema",
                            EndDate = new DateTime(2026, 3, 26, 15, 52, 45, 565, DateTimeKind.Local).AddTicks(8044),
                            Location = "Oficina",
                            Name = "Demo al cliente",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 26, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8043),
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            Description = "Rutina gym",
                            EndDate = new DateTime(2026, 3, 27, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8046),
                            Location = "Gym",
                            Name = "Entrenamiento personal",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 27, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8046),
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 1,
                            Description = "Salida social",
                            EndDate = new DateTime(2026, 3, 28, 17, 52, 45, 565, DateTimeKind.Local).AddTicks(8049),
                            Location = "Restaurante",
                            Name = "Cena con amigos",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8048),
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 1,
                            Description = "Capacitación frontend",
                            EndDate = new DateTime(2026, 3, 19, 17, 52, 45, 565, DateTimeKind.Local).AddTicks(8052),
                            Location = "Centro TI",
                            Name = "Curso de Angular",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 19, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8051),
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 1,
                            Description = "Amistoso internacional",
                            EndDate = new DateTime(2026, 3, 21, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8054),
                            Location = "Estadio",
                            Name = "Partido Bolivia vs Perú",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 21, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8054),
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = 1,
                            Description = "Liberación versión 1.0",
                            EndDate = new DateTime(2026, 3, 22, 15, 52, 45, 565, DateTimeKind.Local).AddTicks(8057),
                            Location = "Servidor",
                            Name = "Deploy producción",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 22, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8056),
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatorId = 2,
                            Description = "Reunión diaria",
                            EndDate = new DateTime(2026, 3, 24, 15, 52, 45, 565, DateTimeKind.Local).AddTicks(8060),
                            Location = "Teams",
                            Name = "Daily Scrum",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 24, 13, 52, 45, 565, DateTimeKind.Local).AddTicks(8059),
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatorId = 2,
                            Description = "Resolución de bugs",
                            EndDate = new DateTime(2026, 3, 24, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8062),
                            Location = "Oficina",
                            Name = "Debug sesión",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 24, 12, 52, 45, 565, DateTimeKind.Local).AddTicks(8062),
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatorId = 2,
                            Description = "Organización tareas",
                            EndDate = new DateTime(2026, 3, 25, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8065),
                            Location = "Zoom",
                            Name = "Planificación sprint",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 25, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8064),
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatorId = 2,
                            Description = "Partido entre amigos",
                            EndDate = new DateTime(2026, 3, 26, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8068),
                            Location = "Cancha",
                            Name = "Partido fútbol",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 26, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8067),
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatorId = 2,
                            Description = "Reunión familiar",
                            EndDate = new DateTime(2026, 3, 27, 17, 52, 45, 565, DateTimeKind.Local).AddTicks(8070),
                            Location = "Casa",
                            Name = "Cena familiar",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 27, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8070),
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatorId = 2,
                            Description = "Code review",
                            EndDate = new DateTime(2026, 3, 28, 15, 52, 45, 565, DateTimeKind.Local).AddTicks(8073),
                            Location = "GitHub",
                            Name = "Revisión código",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 28, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8072),
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatorId = 2,
                            Description = "Corrección urgente",
                            EndDate = new DateTime(2026, 3, 20, 15, 52, 45, 565, DateTimeKind.Local).AddTicks(8076),
                            Location = "Servidor",
                            Name = "Deploy hotfix",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 20, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8075),
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatorId = 2,
                            Description = "Feedback sistema",
                            EndDate = new DateTime(2026, 3, 21, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8078),
                            Location = "Oficina",
                            Name = "Reunión cliente",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 21, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8078),
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatorId = 2,
                            Description = "Pruebas del sistema",
                            EndDate = new DateTime(2026, 3, 22, 16, 52, 45, 565, DateTimeKind.Local).AddTicks(8081),
                            Location = "QA Lab",
                            Name = "Testing QA",
                            ParticipantIds = "[]",
                            StartDate = new DateTime(2026, 3, 22, 14, 52, 45, 565, DateTimeKind.Local).AddTicks(8080),
                            Type = 1
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 2,
                            ReceiverId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 3,
                            ReceiverId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            EventId = 6,
                            ReceiverId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            EventId = 8,
                            ReceiverId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            EventId = 11,
                            ReceiverId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            EventId = 13,
                            ReceiverId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            EventId = 15,
                            ReceiverId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            EventId = 17,
                            ReceiverId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Admin",
                            Email = "douglash.dcz@gmail.com",
                            Password = "YWRtaW4xMjM=",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "John",
                            Email = "juan@gmail.com",
                            Password = "anVhbjEyMw==",
                            Username = "juan"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Maria",
                            Email = "maria@gmail.com",
                            Password = "bWFyaWExMjM=",
                            Username = "maria"
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Carlos",
                            Email = "carlos@gmail.com",
                            Password = "Y2FybG9zMTIz",
                            Username = "carlos"
                        });
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Event", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Agenda.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agenda.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Agenda.Domain.Entities.User", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
